### ISSUE TITLE
Some links are broken

### ISSUE THREAD

**Issue by maxjeblick** [Kipok/NeMo-Skills#2]
Thanks a lot for releasing the models and the datasets!

I noticed that the link in the paper as well as the link in the README (_We release a series of [OpenMath models](https://huggingface.co/collections/nvidia/openmath-65c5619de2ba059be0775014) improved...)_ are broken.

**Comment by Kipok** [comment]
Thanks for reporting this! Can you please try now? Should be fixed

**Comment by maxjeblick** [comment]
Thanks for the quick fix, paper link and README link work now.
