### ISSUE TITLE
Support packing?

### ISSUE THREAD

**Issue by fzyzcjy** [Kipok/NeMo-Skills#214]
Hi thanks for this library! I am looking at OpenMathInstruct-2 and find this repo. I wonder whether this repo supports "packing" or not?

**Comment by shtoshni** [comment]
Can you be more precise in what you mean by "packing"?

**Comment by fzyzcjy** [comment]
Hi, I mean https://huggingface.co/docs/trl/en/sft_trainer#packing-dataset--constantlengthdataset- (the "packing=true" in SFTTrainer)

**Comment by Kipok** [comment]
We do not support training via HuggingFace, but instead use https://github.com/NVIDIA/NeMo-Aligner/. NeMo has support for packed sequences during SFT, but we found that it didn't significantly speed up training and so didn't use it in our experiments. This is most likely since we already have a preprocessing step to remove too large sequences from our data (which doesn't have any impact on final results).

And you can of course use OpenMathInstruct-2 with HF training directly, just not through this repo.

**Comment by fzyzcjy** [comment]
I see, thank you!

**Comment by fzyzcjy** [comment]
@Kipok 

> we already have a preprocessing step to remove too large sequences from our data

I would appreciate it if I could know a bit more details. For example, do you mean the released dataset (on huggingface) is already filtered or not? And if not, what is the seq len threshold?

**Comment by shtoshni** [comment]
The released dataset has the length filtering already performed. For filtering, we used: 
- Maximum length threshold of 1024 tokens (Llama3.1 tokens). 
- Minimum length threshold of 200 characters.

**Comment by fzyzcjy** [comment]
Thank you!

Btw IIRC I saw some questions belong super long (e.g. 2048 tokens) and often contains nonsense repeats. I guess they are due to hallucinations when generating the questions. Thus I wonder maybe we should filter and remove them as well?

**Comment by Kipok** [comment]
Thank for bringing it up @fzyzcjy, that's a good point. I think we overlooked this part and only did filtering on the solutions, not the questions (@shtoshni let me know if I'm wrong here). It does make sense to filter questions out as well, especially if as you say most of the very long ones are not meaningful anyway. I would assume that having the same 1024 token filtering is a good strategy - we can probably run some quick experiments on our side later this week and let you know if there is any effect on the accuracy. Assuming there is only a very small number of those, it shouldn't matter, but good to double check.

**Comment by fzyzcjy** [comment]
Thanks! I also guess it will not affect performances since there are tiny. But I guess removing them may make max sequence length shorter, thus fill in larger batch sizes, thus potentially faster training.

**Comment by shtoshni** [comment]
@fzyzcjy: Thanks for pointing this out because I don't think we used a length-based filter. There were some wrongly-formatted generations we filtered out. For example, generated questions that had the answer in them as well. We also filtered out generations that had multiple questions in them.

**Comment by fzyzcjy** [comment]
You are welcome and looking forward to your further experiments / updates!

**Comment by shtoshni** [comment]
Hi @fzyzcjy, We analyzed our data and found that 564 questions (about 0.1% of all questions) were longer than 1024 Llama3.1 tokens. Removing these long questions from our `train_1M` results in about 880 data points being removed. Using the original `train_1M`, the SFTed model performs 61.22 on the MATH test set. The score gets a minor bump of 61.52 when training on the filtered dataset. From our experience, this performance difference is just noise. But we did observe a performance improvement in our SFT, where we can use a higher micro batch-size per GPU without OOM (4 -> 8). 

Thanks again for bringing this up. We will update the huggingface data page and our repo with these additional findings.

**Comment by fzyzcjy** [comment]
@shtoshni Thank you for the experimental results!

**Comment by shtoshni** [comment]
I'm closing the issue. Thanks again, @fzyzcjy.

**Comment by fzyzcjy** [comment]
@shtoshni You are welcome and also thanks again for the discussion!
