### ISSUE TITLE
Consider open sourcing eval generations

### ISSUE THREAD

**Issue by dylan-slack** [Kipok/NeMo-Skills#8]
Thanks for the awesome repo!

I was curious if you would consider open sourcing the generations from the models themselves used for evaluation? e.g., codellama 7b or codellama 70b etc

While the evaluation script you've provided is quite easy to run (and much appreciated!), from a cost side of things it takes a while to generate the solutions from multiple models, and it would be useful to have access to these generations for analysis & comparison.

Thanks for considering!

**Comment by Kipok** [comment]
Sure! Here are the test set generations for all of the OpenMath models: https://openmath-test-predictions.s3.amazonaws.com/openmath-test-predictions.zip. The file size is ~1gb as it contains predictions from all models across all datasets and 50 samplings for math/gsm8k. After unzipping, you can get a summary of all the metrics by running 

```
python pipeline/summarize_results.py openmath-test-predictions/<model-name>
```

Please let us know if you find any errors in the `is_correct` labels! We know that the grading scripts we use are not perfect and would be happy to fix any common mistakes to make sure the accuracy numbers are more representative of the model's ability to solve math questions.

**Comment by dylan-slack** [comment]
wow thank you! that's amazing
